server:
  port: 10086

spring:
  profiles:
    active: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.118.214:3306/bilibili?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: shijiawei110
#    springboot 2.0以上默认连接池就为hikari 不需要指定
#    type: com.zaxxer.hikari.HikariDataSource

    hikari:
#      在连接池中维护的最小空闲连接数
      minimum-idle: 5
#      最大池大小
      maximum-pool-size: 20
#      从池返回的连接的默认自动提交行为。默认值为true。
      auto-commit: true
#      允许连接在连接池中空闲的最长时间（以毫秒为单位）
      idle-timeout: 30000
      pool-name: DateHikariCPPool
      max-lifetime: 1800000
#      客户端等待连接池连接的最大毫秒数
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    show-sql: false
    open-in-view: true